### ISSUE TITLE
Thread used to evaluate forms changes over time

### ISSUE THREAD

**Issue by cemerick** [nrepl/nrepl#16]
See this thread for reference: https://groups.google.com/forum/#!topic/clojure/UfTQvYNf1-s

When a session is left idle for a little bit of time, the thread id evaluating forms changes. This causes any thread local variables in use to reset to their initial values. This causes strange behavior when doing interactive programming that involves use of thread locals.

The solution is for the same thread to always be used for a given session for as long as the session is open.

(from https://dev.clojure.org/jira/browse/NREPL-80)

**Comment by blueberry** [comment]
I was bitten by this countless times. I thought this was intentionally designed like that! :)

It is not that theread locals are reset, though. They are still in their right place, but since the thread in which the next form is being evaluated changed, the thread locals in that new thread are different, and unset it they have never been set in that new thread.

I came to this thread by looking if there is some API into nREPL's thread pool that would at least enable me to somehow control it from the repl, or at least to automate particular thread locals setting.

I might try to fix this or provide some workaround, but since I am a total nREPL noob, I would need some directions...

**Comment by arrdem** [comment]
Hummmmm pinning per thread definitely makes sense - thread per connection is a well understood pattern - but couldn't you also just read and store the entire thread binding frame at the end of each eval?

**Comment by blueberry** [comment]
I am not sure what are you refering to. Do you mean, do this automatically as a part of nrepl machinery, or manually as a user? If the later, that is exactly the problem: when using 3rd party libraries that maintain their own per-thread context (CUDA in my case) REPL needs constant attention because I never know when the underlying thread is going to change and need to re-setup the context manually each time just in case.

**Comment by arrdem** [comment]
Gotcha. I was referring specifically to the thread local binding state Clojure maintains, not to other JVM thread local state stores. For those yeah single-thread consistency is probably the best fix.

**Comment by bbatsov** [comment]
It seems that really that has to do with the use of `future`s in nREPL (e.g. https://github.com/nrepl/nREPL/blob/master/src/clojure/nrepl/server.clj#L26), as there's no "manual" thread management anywhere - just `future`s and `delay`s if memory serves. 

That's definitely one of the nastier bugs that we need to address.

**Comment by bbatsov** [comment]
> What is seen there is exactly how it behaves: Unbound thread pool with a 30 seconds keep alive time. We could change these with other more convenient values, but I am not sure whether that would have some unintended consequences to the actual futures in the user's application (how are nREPL JVM related to the JVM the user's code run in? I guess it is the same JVM instance.)

I stand corrected. :-) At least now it seems we have a very a good idea how to fix this. ;-) It's the same JVM instance.

> I am not sure how to try this with my copy of Cider+Prelude (and am even not sure should I, since that might break my local copy of Cider, which I still do not know how to repair :)

You just have to build a local copy of nREPL and test with it (using say `cider-connect`). Some barebone instructions are available here http://nrepl.readthedocs.io/en/latest/hacking_on_nrepl/ Afterwards you can start the server with https://github.com/nrepl/lein-nrepl, as unfortunately `lein repl` and `boot repl` still use the legacy tools.nrepl.

**Comment by bbatsov** [comment]
```
 ; ThreadPoolExecutor in JDK5 *will not run* submitted jobs if the core pool size is zero and
    ; the queue has not yet rejected a job (see http://kirkwylie.blogspot.com/2008/10/java5-vs-java6-threadpoolexecutor.html)
    (ThreadPoolExecutor. (if jdk6? 0 1) Integer/MAX_VALUE
                         (long 30000) TimeUnit/MILLISECONDS
                         ^BlockingQueue queue
                         thread-factory)))
```

This code was written when the only JDKs were 5 and 6 and it's a classic example of how not to check for an upper/lower boundary. Guess the intent to was to have the same behaviour of 5 and 6, but now we support only 8+, so we don't care about them. 

It's fine to have many thread pools. I didn't write this code myself, so I'll have to get educated on it as well.

**Comment by bbatsov** [comment]
As discussed with @vspinu I'm reopening this, as #36 solved the problem only partially. Ultimately we'll need to come up with more extensive changes that ensure sessions are mapped to a single thread that never changes.

**Comment by cgrand** [comment]
If you map sessions to threads then it simplifies code a lot (look at all the references to `get-thread-bindings` for a start). However you lose interruptible eval.

Another possibility is to use reflection so as to save thread locals (and inheritable thread locals for exhaustiveness) like we do with thread bindings (actually it would save thread bindings too since they are stored in a ThreadLocal). The catch? Reflection.

**Comment by bbatsov** [comment]
> However you lose interruptible eval.

Yeah, that's a great point. You should also take a look at the subsequent conversation we've had here https://github.com/nrepl/nrepl/issues/62 on the subject.

> The catch? Reflection.

How big of an impact do you think this is going to to have?

**Comment by cgrand** [comment]
Having thought a bit more about it, I have a new proposal:
• allocate a dedicated thread when a session is created by `clone`,
• document that interrupting an eval will cause the thread to be cycled for another one.
