### ISSUE TITLE
Transport/send hangs when sending non-bencodable information outside of :value slot

### ISSUE THREAD

**Issue by cemerick** [nrepl/nrepl#17]
Situation: Writing a CIDER middleware, trying to `transport/send` a response message via the standard bencode transport. The response message has a non-bencodable item outside of the :value slot.

Expected behavior: `transport/send` will bubble up the IllegalArgumentException thrown in c.t.n.bencode/write-bencode due to the non-bencodable item.

Actual behavior: `transport/send` silently fails and hangs. No response is sent over the wire (verified by monitoring communication going across nREPL's port). No exception is bubbled up to the CIDER middleware. Subsequent calls to nREPL (to evaluate code for example) do not return. Once an interrupt is sent, the subsequent calls do return correct values, but the non-bencodable response never appears.

I'm guessing there's some relationship to NREPL-30 (http://dev.clojure.org/jira/browse/NREPL-30)? Please see https://github.com/clojure-emacs/cider-nrepl/issues/332 for further info as well. Let me know if there's anything I can do to debug this issue better.

Thanks for your help,
Sanjay

(from https://dev.clojure.org/jira/browse/NREPL-81)

**Comment by bbatsov** [comment]
@shen-tian You can take at this ticket as point if you want. It's somewhat related to what you've been working on recently.

**Comment by shen-tian** [comment]
I have a guess at what this could be, though not sure if this still happens. Think it's related to differentiating between execution errors, disconnection errors, and actual breakages in nrepl.

**Comment by shen-tian** [comment]
Finally had a dig into this one. I can replicate some behaviour (sending unencodable values, e.g. `(Object.)` in a message seem to cause a stall. This is not unique to the `:value` slot, though I think depending on where in the middleware stack this was done, `print` would have stringyfied any unencodable values in the `:value` slot. This is caused by how `bencode/write-bencode` works: it's recursive. Thus, it will start writing a map, before throwing an Exception that there's unecoded values inside. The fragment of a map, when sent, will cause the reader to stall waiting for "end of the map" that was never written.

- I didn't observe the "nothing sent on the network" effect, but this could be explained by `.flush` not being called after write.
- This did throw an exception for me on the middleware side, but not sure how visible this could have been from a client's point of view, as this error kind of wrecks the transport. This might also be affected by where the `caught` middleware is.

I checked the state of the library circa April 2017, and the analysis holds.

I've prepped a PR that makes the bencode writes fail cleaner.

BTW, does anyone know what's the deal with the `-unencoded` reading code here?

https://github.com/nrepl/nrepl/blob/9b480531d7f2df133f42a5a664d95dcbbf6b92c3/src/clojure/nrepl/transport.clj#L100-L106

I can't find any reference to this in cider or cider-nrepl. What would write `-unencoded`?
