### ISSUE TITLE
Factor out bencode parsing code

### ISSUE THREAD

**Issue by arichiardi** [nrepl/nREPL#32]
The namespace https://github.com/nrepl/nREPL/blob/master/src/clojure/nrepl/bencode.clj is a good candidate for a Clojure/ClojureScript bencode library that if done right could make it easy to develop a ClojureScript version of an nRepl server.

It is pretty nice that we have this there actually.

**Comment by bbatsov** [comment]
Yeah, I agree completely. When I have some time I'll factor this out to another lib here under `nrepl/bencode`.

**Comment by arichiardi** [comment]
On the same theme, props to @PEZ for the work in the Calva plugin: https://github.com/BetterThanTomorrow/calva/blob/master/src/main/calva/repl/nrepl.cljs

A ClojureScript client there, neat!

**Comment by PEZ** [comment]
That’s mostly the work of @pedrorgirardi, but thanks for the recognition!

We are struggling with finding/building a stable foundation for our nrepl communication, and are following initiatives like this with interest. Might there come out a cljc bencode library out of this refactoring?

**Comment by bbatsov** [comment]
@PEZ That's the idea.

**Comment by bbatsov** [comment]
I quickly put together a new project, so @arichiardi (or someone else) can start hacking on it. I'll add some docs later.

**Comment by pedrorgirardi** [comment]
Thank you @bbatsov ! I did a little bit of work with nREPL on Calva with @PEZ , so I'm interested in that. 

We've been working on a new version of Calva written in ClojureScript, and it would be so nice to have a nREPL client in ClojureScript for Node.js. 
There's not much that Calva can do without nREPL/CIDER and we're not that happy with the current nREPL + bencode implementation. 

I would be very keen to try to implement a proper nrepl-client-for-nodejs kind of library with your guidance and @arichiardi .

**Comment by arichiardi** [comment]
Also interested in this for eventually including it lumo. So cljc sounds very good to me :)

**Comment by bbatsov** [comment]
> I would be very keen to try to implement a proper nrepl-client-for-nodejs kind of library with your guidance and @arichiardi .

@pedrorgirardi Happy to help with the guidance. Let me know when you want to start on this, so I can create some repo for you in the nREPL org. I guess that a node client would something useful for many people.

**Comment by bbatsov** [comment]
That's fine. Happy to hear things are working out well for you! 

Btw, what exactly is the purpose the intermediary server plays for you? Just message translation or something more?

**Comment by pedrorgirardi** [comment]
>Btw, what exactly is the purpose the intermediary server plays for you? Just message translation or something more?

The server started as a proxy to nREPL because I didn't want to spend time (at least for now) working on a nREPL client for ClojureScript. I wanted to experiment more with nREPL + CIDER middlware without having to worry about the infrastructure too much.

The project is really an experiment, so I looked at https://github.com/snoe/clojure-lsp too. Clojure LSP is very alpha, but it already has things like renaming a symbol, autocomplete, symbol information, and it works with ClojureScript too. I liked that very much, but I also wanted a REPL, so I thought that it would be nice to be able to extend the Clojure LSP with a 'nREPL extension'.
I forked the project and added a custom method to be able to eval code, and I'm using nREPL for that. I got it working for Clojure & ClojureScript (Figwheel and Shadow CLJS). It's a very basic implementation, but it works.
The server manages the nREPL sessions so the client doesn't know anything about nREPL. All that the VS Code extension does is to send a map with some 'contextual information'  like the nREPL port, the env and which type of ClojureScript REPL it is - all this over LSP, so any LSP client could use this.

I might be very wrong, but I think there could be a good synergy between Orchard and Clojure LSP. LSP is the protocol, but inside the box there is all the common tasks of understanding Clojure code and I think that is common in both projects, isn't it?

Working on Clojure tooling is very new to me, and I honestly have very little experience with this, but I'm enjoying a lot. @PEZ taught me a lot with Calva and showed me that VS Code could have a good Clojure & ClojureScript story.

**Comment by arichiardi** [comment]
@pedrorgirardi that is very cool indeed and I think you are on the right track when you say: Orchard is the implementation, "whatever" is the protocol.

Here the whatever can be bencode + nRepl message payloads or lsp. I have been thinking a lot of having lsp as it has very good integration with editors - nRepl as a protocol was born and adopted at the time where lsp was not around. 

But here comes the fun part: nRepl is already a protocol and to maintain lsp over nRepl would be hard IMHO. Fortunately Clojure has another way to evaluate forms - [socket REPL](https://clojure.org/reference/repl_and_main#_launching_a_socket_server)!

One could use a socket REPL + Orchard in order to implement a semi-platform agnostic tooling set for Clojure. There is even a socket REPL implementation for `lumo`, with same semantics and an ambitious project could aim at targeting Clojure + ClojureScript JVM + ClojureScript self-hosted.

I do not know if I will ever have time to get to that in my lifetime but maybe joining effort could a good idea. The pieces are already kind of here and there, we just need to glue them together like you did already with nRepl. So in case you have something to share - at any stage - or if you are interested in more  details please let me know in here or Slack ok?

**Comment by bbatsov** [comment]
> I might be very wrong, but I think there could be a good synergy between Orchard and Clojure LSP. LSP is the protocol, but inside the box there is all the common tasks of understanding Clojure code and I think that is common in both projects, isn't it?

Yeah, that's a reasonable idea.

> But here comes the fun part: nRepl is already a protocol and to maintain lsp over nRepl would be hard IMHO. Fortunately Clojure has another way to evaluate forms - socket REPL!

You it really be hard, though? You just translate the messages and the responses and you're done. The big advantage nREPL has over the socket REPL is that the protocol is structured similarly to the LSP spec as well (it's basically a RCP protocol with extensible ops), when the socket REPL gives you just evaluation and output handling, so you have to come up with some protocol yourself (although this can also be viewed as feature, I guess). 

There's also the fact that there's still a lot of unextracted functionality from `cider-nrepl` and `refactor-nrepl` that should eventually end up in `orchard`. If you'd like to help with this - that'd be awesome. Right now to support all the features of the spec you'd need just one nREPL server with both middleware libraries and you're done, but if everything gets extracted eventually there would be more options.

> Here the whatever can be bencode + nRepl message payloads or lsp. I have been thinking a lot of having lsp as it has very good integration with editors - nRepl as a protocol was born and adopted at the time where lsp was not around.

True. I'm not vary familiar with the LSP spec, so I have no idea how good fit it is for a Lisp-like language (I remember it has nothing there about evaluation for instance). I just perused the default operations here https://microsoft.github.io/language-server-protocol/specification and that's just a small (but essential I guess) subset of the things we have middleware for right now. I'm assuming that LSP clients can't magically support features that are not in their specs, so for extra functionality you'll always need some extra development done in each client. 

All of that being said - I really think we need some lsp-server for Clojure, and because of all of the tools that currently exist it should be hard to build it. The approach we've discussed in just one of the possible approaches, btw - you can also have an lsp server that provides the core spec simply by doing static analysis of the code (as Cursive does). Depending on your perspective this might a better fit for lsp than the REPL-powered approach that's typically used in Clojure dev tools.

**Comment by bbatsov** [comment]
> The server manages the nREPL sessions so the client doesn't know anything about nREPL. All that the VS Code extension does is to send a map with some 'contextual information' like the nREPL port, the env and which type of ClojureScript REPL it is - all this over LSP, so any LSP client could use this.

That's cool idea, indeed! I'm also wonder if we can't just add some LSP interface straight to nREPL (e.g. a different transport). Anyways, there are always some cool things we can do, but who has the time for all of them? :-)

**Comment by bbatsov** [comment]
And to wrap it up - here are a few references to what I thinking about in the previous comment https://github.com/nrepl/nREPL#transports and https://github.com/nrepl/nrepl/wiki/Extensions After thinking a bit about this I really believe that a nice LSP transport adapter for nREPL might be an interesting way to provide easily support for all LSP capable editors, without doing much extra work.

**Comment by arichiardi** [comment]
> [Would] it really be hard, though? You just translate the messages and the responses and you're done. The big advantage nREPL has over the socket REPL is that the protocol is structured similarly to the LSP spec as well (it's basically a RCP protocol with extensible ops), when the socket REPL gives you just evaluation and output handling, so you have to come up with some protocol yourself (although this can also be viewed as feature, I guess).

I guess you can do the translation - let's say harder than socket REPL. Note that socket REPL in 1.10 introduces prepl and therefore structured messages. I know you know it already, just saying it for completeness.

Either approach of course is great - the end result is to improve things - moving the logic to Orchard was definitely a great move. I will also explore the link you posted, thanks for sharing!

**Comment by bbatsov** [comment]
> I guess you can do the translation - let's say harder than socket REPL. Note that socket REPL in 1.10 introduces prepl and therefore structured messages. I know you know it already, just saying it for completeness.

Why would it be harder? Obviously working with something that exists is easier than with something that doesn't. :-) I'm referring to the fact that things like rename-symbol, xref and so on exist only in `refactor-nrepl` - no one has bother yet to move them to orchard. And there's the slight problem that using the parser to process the Clojure code has to evaluate it, which I guess is not really a problem in most of the languages LSP typically targets (that's the reason why I opted not to include this in CIDER originally - it confuses too many people). 

For prepl my reservation is that it will be one of those one off abandonware efforts (Cognitect has this habit of releasing new stuff and forgeting about them). And, of course, you'd be getting fixes there once a year if you're lucky. :-) Hopefully this won't be the case, but time will tell.

**Comment by arichiardi** [comment]
Maybe harder is not the right word here, but I am specifically referring to the mere fact that there are many more moving parts: lsp over nRepl which uses Orchard vs lsp over socket REPL that uses Orchard _seems_ simpler to manage and to debug in case of problems for a green field project.

At least _I_ would start from simpler, then if I see that I need transports and extensions mechanisms I would definitely consider introducing nRepl. In terms of contributions to the current tooling you would of course get the benefits because Orchard is shared.

I don't see the parsing problem, socket REPL evaluates forms - lsp's payload would be a string I...maybe missing something about internals? I would like to understand this better as for sure ;out have more experience than me :wink:

About prepl...well I don't know, valid concern, it has not even been released and probably with the slow pace of Clojure releases it will take a while to get in officially.
