### ISSUE TITLE
Publish the API reference docs

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nREPL#41]
We can probably replicate the approach taken by @gonewest818 for orchard (https://clojure-emacs.github.io/orchard/master/). 

Or maybe check that new service by @martinklepsch (https://github.com/cljdoc/cljdoc)?

**Comment by martinklepsch** [comment]
Docs for nREPL are already on cljdoc: https://cljdoc.xyz/d/nrepl/nrepl/0.4.4

The sidebar is a bit of a mess because cljdoc tries to incorporate all the files in `doc/` but you can easily clean that up by adding a `doc/cljdoc.edn` file as [described in the guide](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#configuring-articles).

I'd also offer to do this for you but I don't want to deprive myself of the chance to receive some feedback on the whole process so I'll wait a bit before offering to do it 😛 

If you end up trying it, either push SNAPSHOTs and have a `cljdoc.edn` file on your master branch or [build things locally without pushing anything to Clojars or GitHub](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#building-docs-locally).

**Comment by bbatsov** [comment]
Oh, that's awesome! I thought I should probably probably do something myself to get the docs there.

> I'd also offer to do this for you but I don't want to deprive myself of the chance to receive some feedback on the whole process so I'll wait a bit before offering to do it 😛

@martinklepsch Yeah, that's easy enough, I just wonder how I'll be able to reconcile RTD/mkdocs and cljdoc. :-)

**Comment by martinklepsch** [comment]
I think you should be able to incorporate all the Markdown files you use for RTD into cljdoc. Just use the `cljdoc.edn` file to describe the hierarchy and nesting you want. 

One of the goals of cljdoc is to have API and non-API docs (= “articles”) in the same place so users can easily jump between them without too many clicks or reorienting themselves.
