### ISSUE TITLE
Make it possible to limit the size of returned values and output

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#75]
Some clients (e.g. Emacs) can't handle very well huge strings in their REPL buffers. It's also questionable how good UX this constitutes as well. 

Ideally we should be able to specify some value/output limit in eval ops, so that we can trim the result accordingly. We can either return the full and trimmed results in the same message or just have clients request to eval the same code again without any size limits if they happen to need the big result. 

See https://github.com/clojure-emacs/cider/issues/1115 and https://github.com/clojure-emacs/cider/issues/2507 for more details. @gonewest818 started working on something very similar a while back (https://github.com/clojure-emacs/cider/issues/1115#issuecomment-374487527), so someone might pick up his work if they want to, even though a simpler approach with no caching of the results/output will be fine as well.

**Comment by bbatsov** [comment]
@behrica As that's strictly CIDER specific it'd be best to convert this into a CIDER issue. You're making some valid points, but they are somewhat orthogonal to what we're trying to solve here.

**Comment by behrica** [comment]
I have a more general comment , which belongs here:

I think a good truncation strategy is very difficult to come up with.

Because there are at least two very orthogonal data structures which makes problems:

- huge sequences of rather small elements
- huge individual strings inside short sequences

(and everything inbetween)

Every "truncate" function need to pick some cases of structures (seqs, maps, strings, keywords) it wants to check for "too long" and truncate them.
it is always a kind of "white list" and at a certain point something unexpected will come, it will let it through and emacs will choke on it.  This is true for a default truncater, but as well for the user supplied truncation function.

And the how large is "too large" question, depends on may factors as well.
This makes the concept of "truncation" hard to get right.

Maybe instead of "truncation" nrepl should fail, 
if the "result" is longer then a configured number of bytes.

I see the main use case for this feature to prevent user mistakes, as he "by accident" evaluates a very complex data structure.
So the questions of truncating into valid structures is not important to me.

In my view, the "truncation" should happen only, because I did a mistake.
In this perspective, an "error" on large responses might be as good as truncation (and simpler)

I would like to see a feature which lets me decide "how many bytes at max" I get when "I press return in the repl".  (and this is **guaranteed**, what ever data structure I get)
So I can set this to 10000. In this case I would be happy, if something simply fails, if my response is too long. (Because it probably means that I have a wrong assumption on the thing I evaluate.
In reality I never need responses "larger then my screen")

This is a similar idea the "Tidyverse" R package implements for printing of data frames.
The result of "printing" a data frame is never larger then a screen size.

What could be maybe added to this, is that the responses get always in full serialized to disk...(on truncation or failure)
This would solve the main inconvenience of  simple  "failing" / "truncating", which is the loosing of an a bit too long result from a long running computation.

Some type of feedback of the "bytes received and dropped" would be usefull as well.

**Comment by bbatsov** [comment]
I want to briefly follow-up on this - after some experimentation (thanks a lot @pfeodrippe!) we've decided that this approach was fundamentally flawed. We've opted in a different direction - bringing Unrepl's handling for collections (elided collections) to nREPL).

**Comment by bbatsov** [comment]
Closing in favour of #92.

**Comment by pfeodrippe** [comment]
Awesome! Anxious to see it \o/
